# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE      = attiny85
CLOCK      = 8000000
PROGRAMMER = -c usbtiny 
OBJECTS    = ps2tandy.o
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES       = -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

# symbolic targets:
all:	ps2tandy.hex

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:ps2tandy.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID ps2tandy.hex

clean:
	rm -f ps2tandy.hex ps2tandy.elf $(OBJECTS)

# file targets:
ps2tandy.elf: $(OBJECTS)
	$(COMPILE) -o ps2tandy.elf $(OBJECTS)

ps2tandy.hex: ps2tandy.elf
	rm -f ps2tandy.hex
	avr-objcopy -j .text -j .data -O ihex ps2tandy.elf ps2tandy.hex
#	avr-size ps2tandy.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	ps2tandy.elf
	avr-objdump -d ps2tandy.elf
